### ISSUE TITLE
Improve Codebase for Xcode 16.0 compatibility and Integration with Marker Data

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#110]
https://github.com/TheAcharya/MarkerData/issues/106

@orchetect When you have time you can tweak the codebase. 

And @milanvarady could make the necessary tweaks back in Marker Data.

Thank you.

**Comment by orchetect** [comment]
I've updated the codebase for compatibility with Xcode 16 / Swift 6,

I also refactored some internal code related to image generation to use modern Swift Concurrency async/await patterns, which has cleaned it up a bit and should make it safer.

Next I can have a look at Marker Data and see what conformances @milanvarady has added there to types exported from MarkersExtractor. From what I saw, it's mostly `Identifiable` conformances. Those I may move to MarkersExtractor since that's a common protocol used with SwiftUI and would not only be beneficial to anyone using MarkersExtractor as a library. But it's also better coding architecture, which is the reason for the compile warnings in the first place.

**Comment by orchetect** [comment]
Ok I've done the appropriate refactors and will release 0.3.10 shortly.

I am making the necessary counter-adjustments to Marker Data on a separate branch and will push a Pull Request to the Marker Data once MarkersExtractor 0.3.10 is ready.

**Comment by IAmVigneswaran** [comment]
Thank you!

**Comment by orchetect** [comment]
I've been updating my other open-source libraries and apps for new language features, Swift Concurrency, and better compatibility with Xcode 16 and the Swift 6 toolchain.

So a couple of dependencies have been improved (TimecodeKit, DAWFileKit) and some API has changed (mostly making various methods async), so I will push a MarkersExtractor 0.3.11 update with the needed changes in the codebase.

I already refactored MarkersExtractor itself to utilize Swift Concurrency a while ago, so not a lot of changes or improvements are really needed internally. But I can have a look through and see if anything needs polish at some point.

**Comment by orchetect** [comment]
Will close this, as this is done.

**Comment by IAmVigneswaran** [comment]
> Will close this, as this is done.

Thank you!
