### ISSUE TITLE
Profiles & Formats (MIDI File)

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#23]
Ability to translate FCP's Marker Metadata into ProTools importable/compatible Marker file.

More details will be added soon.

https://www.soundsinsync.com/products/edimarker

**Comment by orchetect** [comment]
I have a lot of experience with Pro Tools and have spent years dealing with marker import/export with it.

To export from PT, the most reliable way is to use its session info text file.
DAWFileKit has a 100% parsing implementation for it and is fully unit tested, so it would be very easy to implement in MarkersExtractor as an **import format** instead of FCPXML.
The reason is that this is an export-only format from Pro Tools. Pro Tools does not read/import it.

In order to get markers into Pro Tools, it's much harder/jankier:
- It's almost impossible to write a native Pro Tools session file (.ptx) because it's proprietary and encrypted.
- AAF is an absolute pain to deal with
- DAWFileKit can write MIDI files with markers at a static tempo which any DAW can import, including Pro Tools. So this would be easy to implement in MarkersExtractor.

**Comment by IAmVigneswaran** [comment]
> DAWFileKit can write MIDI files with markers at a static tempo which any DAW can import, including Pro Tools. So this would be easy to implement in MarkersExtractor. This format isn't the most ideal for end-users but it works.

A black audio/midi file with Markers, would be better than nothing!

**Comment by orchetect** [comment]
Yes, as odd as it sounds, one of the most baseline and reliable way of getting markers into a Pro Tools session is importing a MIDI file.

Incidentally, over the years I fully developed the logic to write a MIDI file with marker events that import with precision to their timecode locations for this exact reason.

**Comment by orchetect** [comment]
MIDI File export is 95% done. Will push soon.

As explained above, it is virtually the only way to get markers into Pro Tools.

Another benefit is that MIDI files can be imported into other DAWs like Logic, Cubase, etc. in addition to Pro Tools.

**Comment by IAmVigneswaran** [comment]
I was just trying to import the `.mid` file in Logic Pro. I did not see any markers on when I toggle down the Marker track. 

I am not sure if it is supposed to work in this when importing. Am I missing something?

**Comment by orchetect** [comment]
Ok so after some testing and Googling, it appears that Logic is stupid. (Surprise, surprise).

You can't import markers directly into an existing project. But if you open the MIDI file itself as a new file, then it works and you can then copy them to an existing project.

1. Drag MIDI file onto Logic's app icon, or select menu _File → Open_ and choose the MIDI file
2. You may need to drag the project end handle to the right to be able to see all the markers, as it will interpret the project to only be a bar long on first open
3. Open the Marker List window
4. Select all in the list window
   - Select menu: _Options → Lock SMPTE Position_
   - (Optional) Select menu: _View → Show Event Position and Length as Time_ (this will display timecode instead of bars & beats)
   - While all markers are still selected, select menu: _Edit → Copy_
   - Note the timecode of the earliest marker for reference later
5. Open the existing project you want to bring the markers into
6. Check the project's start timecode
   - Select menu: _File → Project Settings → Synchronization..._
   - Ensure that `Bar Position <first bar>` is set to a timecode that is equal to or earlier than the first marker's timecode
7. In the project window, select menu: _Edit menu → Paste at Original Position_

**Comment by IAmVigneswaran** [comment]
>  it appears that Logic is stupid. (Surprise, surprise).

Every app has it own list of quirks. Haha.

> Drag MIDI file onto Logic's app icon, or select menu File → Open and choose the MIDI file

Thanks for the instructions. I am able to view the Markers in Logic Pro. 

<img width="1035" alt="Screenshot 2023-04-29 at 8 46 09 AM" src="https://user-images.githubusercontent.com/118706051/235273732-19433e2a-3232-4b5e-b927-c333d2bcca44.png">

I am also able to copy and paste the Markers from one project to another.
