### ISSUE TITLE
Full robust support of a different frame rates

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#3]
In the current build, the tool does not handle drop-frame rates correctly.

In the next and subsequent builds, the tool should process different frame rates (those which are supported by FCP) correctly.

**Final Cut Pro's supported frame rates.**
`23.98`, `24`, `25`, `29.97`, `30`, `50`, `59.94` & `60`.

<img width="635" alt="FCP-Frame-Rate" src="https://user-images.githubusercontent.com/118706051/207214908-641df9a5-d8a1-4657-bab0-dc3f5aeb7543.png">

**Comment by orchetect** [comment]
All these rates (including interlaced rates like 25i, 29.97i) are supported by TimecodeKit.

This is probably the first refactor - importing TimecodeKit as a dependency and letting it handle timecode and frame rate conversions.

**Comment by orchetect** [comment]
I've now implemented this, but have only tested a handful of frame rates. So far it's resulting in correct output.

**Comment by orchetect** [comment]
All progressive frame rates should be working reliably. What I haven't tested is interlaced rates because I don't have any interlaced video on hand.

@IAmVigneswaran are you able to test with **25i** and **29.97i**?

**Comment by IAmVigneswaran** [comment]
@orchetect Sure! Will report back soon using the current build of the tool.

**Comment by IAmVigneswaran** [comment]
@orchetect I don't have interlaced clips. But I have converted couple of timelines to 25i and 29.97i.

With the 0.1.1 build that I have tested with, I notice Marker timecode drift.

**Comment by orchetect** [comment]
We need to be testing with the head of the main branch. Are you able to compile it?

**Comment by IAmVigneswaran** [comment]
> We need to be testing with the head of the main branch. Are you able to compile it?

Nope. Could you send me a pre-compiled binary?

**Comment by orchetect** [comment]
Using the latest build, I tested the 25i FCP project you sent over. It's working perfectly.

<img width="563" alt="25i" src="https://user-images.githubusercontent.com/11605557/210126799-44ef295d-c654-4c65-8fa6-dc9234ce8446.png">

However what you will notice is that in the FCP sequence, markers actually are not perfectly on frame starts. They have subframes > 0. This likely happened when you took the old FCP project (which was at a different incompatible frame rate) and changed it to 25i.

Having timecode output with truncated subframes is fine for our purposes. We could however allow subframes to be output in the CSV very easily. My suggestion is that we only enable subframes output in CSV if subframes are > 0. The reason is that many projects will not have subframes in their timecode since FCP defaults to inserting markers at frame starts. The only time you run into this odd situation we have here is when mixing frame rates or converting projects between frame rates.

If we want to discuss subframes, we should open a new Issue as that is a new feature.

**Comment by orchetect** [comment]
I'll close this issue, as we've basically tested all frame rates now.

**Comment by orchetect** [comment]
Opened a new issue to address subframes - #29
