### ISSUE TITLE
Markers outside the boundaries of Clip's Duration

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#34]
@orchetect The tool's current behaviour will process all the Markers even if they are not shown in the timeline & index.

![Marker_boundaries](https://user-images.githubusercontent.com/118706051/210218480-cdfa34b5-39bd-4b88-b68e-9f9d49d2e396.gif)

Should we ignore Marker when they are outside of Clip's duration boundaries?

`--include-clip-boundaries` with `true` or `false` option. The default would be `false`.

**Comment by orchetect** [comment]
Agreed - feels like an intuitive additional.

Although I would name the CLI flag something more clear. Probably `--include-outside-clip-boundaries`.

With the default (`false`), should we still log out-of-clip-bounds markers like we presently do? I think it's useful feedback. Perhaps the log entry level could be demoted from "WARNING" to "NOTICE" or "INFO", since it's more informational and not dangerous or detrimental to the process.

**Comment by orchetect** [comment]
Just a small note on the CLI:

Even though the CLI help block groups flags and options together under "OPTIONS:", there is an important distinction in practise:

FYI, all of our CLI **flags** do not need a trailing `true` or `false` parameter - and the argument parser actually won't accept a trailing parameter for them. All of our flags as opt-in (`false` by default). If the flag is supplied, it's true. If the flag is not supplied, it's false. So we use grammar that evokes the opt-in behavior, and that's also why the CLI help block does not state a "(default: )" for flags.

CLI **options** can take a trailing parameter which is almost never a boolean since it would be inconsistent syntax with how flags work.

**Comment by orchetect** [comment]
This also reminds me: currently we log the out of bounds marker warning message only if the marker is beyond the right side of the clip, but it's possible for markers to be out of bounds on the left side too. Those should be logged too.

https://github.com/TheAcharya/MarkersExtractor/blob/0b1547310f10cfc3c62313fcfecae82f2bcd0f49/Sources/MarkersExtractor/Extractors/FCPXMLMarkerExtractor.swift#L161-L163

- [ ] Log out-of-bounds markers that are earlier than the clip start

**Comment by IAmVigneswaran** [comment]
> Although I would name the CLI flag something more clear. Probably --include-outside-clip-boundaries.

Yes! `--include-outside-clip-boundaries` is more clear. 

Yes, we could have something like `WARNING: Markers outside of clip boundaries detected. There are not included in the export.` before the tool starts the process?

> FYI, all of our CLI flags do not need a trailing true or false parameter - and the argument parser actually won't accept a trailing parameter for them. All of our flags are opt-in (false by default). If the flag is supplied, it's true. If the flag is not supplied, it's false. So we use grammar for the flag name that evokes the opt-in behavior, and that's also why the CLI help block does not state a "(default: X)" for flags.

Thanks for the explanation! If I understand correctly, if we don't enter the option flag, it will be `false`. Only when we provide it, it becomes `true`.

> This also reminds me: currently we log the out of bounds marker warning message only if the marker is beyond the right side of the clip, but it's possible for markers to be out of bounds on the left side too. Those should be logged too.

Yes, we can trim clips in both left and right side.

**Comment by orchetect** [comment]
> [...] we could have something like `WARNING: Markers outside of clip boundaries detected. There are not included in the export.` before the tool starts the process?

I like the existing behavior of logging one line per marker that is found out of bounds. It helps users diagnose because when working with a FCP project, it's almost impossible to know where these are because FCP hides them from the timeline and the Tag list.

> If I understand correctly, if we don't enter the option flag, it will be `false`. Only when we provide it, it becomes `true`.

Yes exactly.

**Comment by orchetect** [comment]
This is done. Will be in next alpha.
