### ISSUE TITLE
Colour Palette Generator

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#47]
@orchetect I have an interesting idea. I am not sure if it is feasible with our tool. This idea is inspired by [ShotDeck](https://shotdeck.com/). 

In ShotDeck, all the images have a colour palette generated dynamically.

<img width="1051" alt="ShotDeck" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/cb66707f-5c5b-44fe-ba79-9ddac2c2bea8">

I wonder if we can achieve something similar. It could be something like `--enable-colour-palette`. Once enable the tool would analyse the dominant colours from image and append the colour palette it to the bottom of the image. We can add options, on how maybe palette it should generator.

For example -

![Sample](https://github.com/TheAcharya/MarkersExtractor/assets/118706051/0c466e23-80d1-47a1-84ae-d9fda7d6e842)

I found some open source projects that does this.
https://github.com/bd452/swift-vibrant
https://github.com/yamoridon/ColorThiefSwift
https://github.com/elliotekj/distil
https://github.com/Boris-Em/ColorKit

Use cases -
- Referencing during colour grading
- Cinematography and Shot List Database

**Comment by orchetect** [comment]
Image post-processing aside from the existing text labelling capabilities of MarkersExtractor is kind of outside the scope of the core purpose of MarkersExtractor. The library already has a lot of parameters and not enough unit testing as is to even check a small fraction of them currently. I would like to avoid adding optional features that could be accomplished by other means.

For your own use, conceivably a dedicated CLI tool must exist (perhaps at one of those repos) that can modify image files with these swatches. If it doesn't accept a folder or multiple files via command line arguments, a simple bash script could iterate through all image files in the output folder after MarkersExtractor runs.

If you're intent on adding post-processing like this to Marker Data then perhaps one of these libraries could be integrated in the application instead of MarkersExtractor itself.

**Comment by IAmVigneswaran** [comment]
> Image post-processing aside from the existing text labelling capabilities of MarkersExtractor is kind of outside the scope of the core purpose of MarkersExtractor. The library already has a lot of parameters and not enough unit testing as is to even check a small fraction of them currently. I would like to avoid adding optional features that could be accomplished by other means.

No doubt it would be a cool and productive feature. Yes, it does seems outside the scope of our MarkersExtractor library.

> If you're intent on adding post-processing like this to Marker Data then perhaps one of these libraries could be integrated in the application instead of MarkersExtractor itself.

Having a post-processing method for Marker Data could be one way to add this feature. I can look into this at some point once Marker Data is release to public.

**Comment by orchetect** [comment]
If you want to pursue that, go ahead. But this would be a low priority feature for MarkersExtractor as there are many more pressing issues.

**Comment by IAmVigneswaran** [comment]
> If you want to pursue that, go ahead. But this would be a low priority feature for MarkersExtractor as there are many more pressing issues.

Absolutely!
